version: 2
updates:
  # Enable version updates for Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "radicand"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore"
      prefix-scope: "deps"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "all"
    ignore: [] # Remove this if you want to ignore specific dependencies
